steps:

- id: 'Test'
  name: 'docker/compose:1.25.0-rc2-alpine'
  args: ['run', '-T', 'app', 'test']

- id: 'Build'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', '${_IMAGE_NAME}:${SHORT_SHA}', '-t', '${_IMAGE_NAME}:latest']

- id: 'Push'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}:${SHORT_SHA}']

- id: 'Push as latest'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}:latest']

- id: 'Deploy'
  name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
    - 'run'
    - '--filename=$_K8S_DEPLOYMENT_PATH'
    - '--image=$_IMAGE_NAME:$SHORT_SHA'
    - '--app=$_K8S_APP_NAME'
    - '--version=$SHORT_SHA'
    - '--namespace=$_K8S_NAMESPACE'
    - '--label=$_K8S_LABELS,gcb-build-id=$BUILD_ID'
    - '--cluster=$_GKE_CLUSTER'
    - '--location=$_GKE_LOCATION'

- id: 'Migrate'
  name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'run'
    - '${_K8S_APP_NAME}-${SHORT_SHA}-migrate'
    - '--image=${_IMAGE_NAME}:${SHORT_SHA}'
    - '--namespace=${_K8S_NAMESPACE}'
    - '--filename=${_K8S_RUN_POD_PATH}'
    - '--generator=run-pod/v1'
    - '--restart=Never'
    - '--attach'
    - '--rm'
    - '--'
    - 'migrate'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_GKE_LOCATION}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

tags:
  - 'gcp-cloud-build-deploy'
  - '$_K8S_APP_NAME'

substitutions:
  _GKE_CLUSTER: 'gardinte'
  _GKE_LOCATION: 'us-east1-b'
  _K8S_APP_NAME: 'gardinte-app'
  _K8S_DEPLOYMENT_PATH: 'manifests/deployment.yml'
  _K8S_RUN_POD_PATH: 'manifests/pod.yml'
  _K8S_NAMESPACE: 'development'
  _K8S_LABELS: 'app=gardinte-app'
  _IMAGE_NAME: 'gcr.io/k8s-gardinte-development/ist'
