steps:

- id: 'Test'
  name: 'gcr.io/cloud-builders/docker'
  args: ['docker-compose', 'run', '-T', 'app', 'test']

- id: 'Build'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', '${_IMAGE_NAME}:${SHORT_SHA}', '-t', '${_IMAGE_NAME}:latest']

- id: 'Push'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}:${SHORT_SHA}']

- id: 'Push as latest'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}:latest']

- id: 'Deploy'
  name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
    - 'run'
    - '--filename=$_K8S_YAML_PATH'
    - '--image=$_IMAGE_NAME:$SHORT_SHA'
    - '--app=$_K8S_APP_NAME'
    - '--version=$SHORT_SHA'
    - '--namespace=$_K8S_NAMESPACE'
    - '--label=$_K8S_LABELS,gcb-build-id=$BUILD_ID'
    - '--cluster=$_GKE_CLUSTER'
    - '--location=$_GKE_LOCATION'

images: ['${_IMAGE_NAME}:${SHORT_SHA}']

tags:
  - 'gcp-cloud-build-deploy'
  - '$_K8S_APP_NAME'

substitutions:
  _GKE_CLUSTER: 'gardinte'
  _GKE_LOCATION: 'us-east1-b'
  _K8S_APP_NAME: 'gardinte-app'
  _K8S_YAML_PATH: 'manifests'
  _K8S_NAMESPACE: 'development'
  _K8S_LABELS: 'app=gardinte-app'
  _IMAGE_NAME: 'gcr.io/k8s-gardinte-development/ist'
