steps:

- id: 'build'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/${_PROJECT}/${_APP}']

- id: 'deploy'
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/${_DEPLOYMENT}', 'app=gcr.io/${_PROJECT}/${_APP}']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

images: ['gcr.io/${_PROJECT}/${_APP}']

substitutions:
  _APP: ist
  _CLUSTER: gardinte
  _DEPLOYMENT: gardinte-app
  _PROJECT: k8s-gardinte-development
  _ZONE: us-east1-b

tags: ['gardinte']
