steps:

- id: 'build'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/${PROJECT}/${APP}']

- id: 'deploy'
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/${DEPLOYMENT}', 'app=gcr.io/${PROJECT}/${APP}']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${CLUSTER}'

images: ['gcr.io/${PROJECT}/${APP}']

substitutions:
  APP: ist
  CLUSTER: gardinte
  DEPLOYMENT: gardinte-app
  PROJECT: k8s-gardinte-development
  ZONE: us-east1-b

tags: ['gardinte']
