version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
    image: gardinte/app-test
    ports:
      - '4000:4000'

  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ist
      POSTGRES_PASSWORD: ist
      POSTGRES_DB: ist_test
    ports:
      - '5433:5432'
