apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardinte-app
  labels:
    app: gardinte-app
spec:
  selector:
    matchLabels:
      app: gardinte-app
  template:
    metadata:
      labels:
        app: gardinte-app
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: ltv-app
          livenessProbe:
            httpGet:
              path: /healthy
              port: 80
          readinessProbe:
            httpGet:
              path: /healthy
              port: 80
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config-volume
              subPath: nginx.conf
        - name: app
          image: gcr.io/gardinfra-development/ist
          ports:
            - containerPort: 4000
              name: gardinte-app
          livenessProbe:
            httpGet:
              path: /sessions/new
              port: 4000
          readinessProbe:
            httpGet:
              path: /sessions/new
              port: 4000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: databaseUrl
                  name: gardinte-app-secrets
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  key: secretKeyBase
                  name: gardinte-app-secrets
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  key: sendgridApiKey
                  name: gardinte-app-secrets
            - name: BUCKET
              valueFrom:
                configMapKeyRef:
                  key: bucket
                  name: gardinte-app-config
      volumes:
        - name: nginx-config-volume
          configMap:
            name: gardinte-app-config-nginx
