apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gardinte-app
  labels:
    app: gardinte-app
spec:
  selector:
    matchLabels:
      app: gardinte-app
  template:
    metadata:
      labels:
        app: gardinte-app
    spec:
      containers:
        - name: app
          image: gcr.io/gardinfra-development/ist
          ports:
            - containerPort: 4000
              name: gardinte-app
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /sessions/new
              port: 4000
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /sessions/new
              port: 4000
              scheme: HTTP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: databaseUrl
                  name: gardinte-app-secrets
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  key: secretKeyBase
                  name: gardinte-app-secrets
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  key: sendgridApiKey
                  name: gardinte-app-secrets
      volumes:
        - name: secret-volume
          secret:
            secretName: gardinte-app-secrets
